config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # devise_scope :admin do
  #   post 'admin/guest_sign_in', to: 'admin/sessions#guest_sign_in'
  # end

  get "users/my_page", to: "public/users#my_page", as:"my_page"
  get "users/infomation/edit", to: "public/users#edit", as:"info_edit_user"

  scope module: "public" do
    root to: "homes#top"
    get "users/unsubscribe"
    patch "users/withdraw"
    resources :rooms, only: [:create, :show]
    resources :users, only: [:edit, :update, :show] do
      resources :messages, only: [:create, :index]
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :post_images do
      get :search, on: :collection
      get :confirm, on: :collection
      resource :post_image_favorites, only: [:create, :destroy]
      resources :post_image_comments, only: [:create, :destroy]
    end

    resources :post_lost_cats do
      resource :post_lost_cat_favorites, only: [:create, :destroy]
      resources :post_lost_cat_comments, only: [:create, :destroy]
    end
  end


  namespace :admin do
    get "/" => "homes#top", as: "top"
    resources :users, only: [:show, :edit, :update]
    resources :types, only: [:index, :new, :create, :destroy]
    resources :post_images, only: [:index, :show, :destroy]
    resources :post_lost_cats, only: [:index, :show, :destroy]
    resources :post_image_comments, only: [:index, :destroy]
    resources :post_lost_cat_comments, only: [:index, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  belongs_to :type
  has_many :post_image_favorites, dependent: :destroy
  has_many :post_image_comments, dependent: :destroy

  validates :image,presence: true
  validates :title, length: { maximum: 20 }
  validates :body, length: { maximum: 100 }

  enum sex: {
    male: 0, female: 1, unknown: 2
  }

  enum status: {
    published: 0, draft: 1
  }

  def favorited_by?(user)
     post_image_favorites.exists?(user_id: user.id)
  end

  def self.create_all_ranks
    PostImage.find(PostImageFavorite.group(:post_image_id).order('count(post_image_id) desc').limit(3).pluck(:post_image_id))
  end
end

app/controllers/admin/post_images_controller.rb
class Admin::PostImagesController < ApplicationController
  def index
    @post_images = PostImage.published
  end

  def show
    @post_image = PostImage.find(params[:id])
    @user = @post_image.user
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to admin_post_images_path
  end
end

app/helpers/admin/post_images_helper.rb
module Admin::PostImagesHelper
end

app/views/admin/post_images/destroy.html.erb
<h1>Admin::PostImages#destroy</h1>
<p>Find me in app/views/admin/post_images/destroy.html.erb</p>

app/views/admin/post_images/index.html.erb
<div class="cover-index">
  <div class="container">
    <div class="row text-center mt-5 mb-5">
      <div class="col-7 text-right admin-subtitle">
        <h2>投稿一覧</h2>
      </div>
      <div class="col-5 text-right">
        <%= link_to "迷子猫一覧", admin_post_lost_cats_path, class:"btn btn-outline-info rounded-pill" %>
      </div>
    </div>
    <div class="row justify-content-center">
      <% @post_images.each do |post_image| %>
        <% if post_image.image.attached? %>
          <div class="one-post">
            <p class="caption"><%= post_image.title.truncate(10, omission: "...") %></p>
            <%= link_to admin_post_image_path(post_image) do %>
              <%= image_tag post_image.image, class:"image-shape" %>
            <% end %>
            <p class="caption"><%= post_image.user.user_name %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/post_images/show.html.erb
<div class="container">
  <div class="row text-center mt-5 mb-5">
    <div class="col mx-auto admin-subtitle">
      <h2>投稿詳細</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-6 text-right">
      <% if @post_image.image.attached? %>
        <%= image_tag @post_image.image, class:"image-show" %>
      <% end %>
    </div>
    <div class="col-6">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td class="admin-table">投稿日</td>
            <td><%= @post_image.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <td class="admin-table">ユーザー</td>
            <td><%= link_to "#{@user.user_name}", admin_user_path(@user) %></td>
          </tr>
          <tr>
            <td class="admin-table">猫種</td>
            <td><%= @post_image.type.name %></td>
          </tr>
          <tr>
            <td class="admin-table">性別</td>
            <td><%= @post_image.sex_i18n %></td>
          </tr>
          <tr>
            <td class="admin-table">タイトル</td>
            <td><%= @post_image.title %></td>
          </tr>
          <tr>
            <td class="admin-table">本文</td>
            <td><%= @post_image.body %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row mt-5 mb-5">
    <div class="col text-center">
      <%= link_to "投稿を削除", admin_post_image_path(@post_image), method: :delete, data: { confirm: "削除しますか？" }, class: "btn btn-outline-danger rounded-pill" %>
    </div>
  </div>
</div>