config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # devise_scope :admin do
  #   post 'admin/guest_sign_in', to: 'admin/sessions#guest_sign_in'
  # end

  get "users/my_page", to: "public/users#my_page", as:"my_page"
  get "users/infomation/edit", to: "public/users#edit", as:"info_edit_user"

  scope module: "public" do
    root to: "homes#top"
    get "users/unsubscribe"
    patch "users/withdraw"
    resources :rooms, only: [:create, :show]
    resources :users, only: [:edit, :update, :show] do
      resources :messages, only: [:create, :index]
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :post_images do
      get :search, on: :collection
      get :confirm, on: :collection
      resource :post_image_favorites, only: [:create, :destroy]
      resources :post_image_comments, only: [:create, :destroy]
    end

    resources :post_lost_cats do
      resource :post_lost_cat_favorites, only: [:create, :destroy]
      resources :post_lost_cat_comments, only: [:create, :destroy]
    end
  end


  namespace :admin do
    get "/" => "homes#top", as: "top"
    resources :users, only: [:show, :edit, :update]
    resources :types, only: [:index, :new, :create, :destroy]
    resources :post_images, only: [:index, :show, :destroy]
    resources :post_lost_cats, only: [:index, :show, :destroy]
    resources :post_image_comments, only: [:index, :destroy]
    resources :post_lost_cat_comments, only: [:index, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/7e95dcb8da.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@100;200;400&family=Zen+Maru+Gothic:wght@300;400&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="content">
      <header class="shadow-sm pt-3 pb-3">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container header" style="flex-wrap: wrap">
            <div class="col-4 welcome-wrapper">
              <div class="navbar-nav welcome">
                <% if user_signed_in? %>
                   Welcome, <br><%= current_user.user_name %>!
                <% end %>
              </div>
            </div>
            <div class="col-4">
              <div class="mx-auto">
                <div class="nav2">
                  <%= link_to image_tag("meow-title2.png", class:"logo_img"), "/" %>
                </div>
              </div>
            </div>
            <div class="col-12 col-sm-4">
              <div class="post_image_search">
                <%= form_with url: search_post_images_path, method: :get, local: true do |f| %>
                <div class="search_box">
                  <%= f.text_field :search, class: "form-control search_field ", placeholder: "キーワード検索" %>
                  <%= f.submit "Go", class:"go-button" %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="offset-9 col-3 text-right humberger-menu">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            </div>
            <div class="offset-2 col-8 menu">
              <div class="mx-auto">
                <div class="collapse navbar-collapse flex-column row" id="navbarNavDropdown" style="align-items: normal">
                  <ul class="navbar-nav text-center">
                    <% if user_signed_in? %>
                      <li class="col text-nowrap"><%= link_to "New post", new_post_image_path %></li>
                      <li class="col text-nowrap"><%= link_to "Cats", post_images_path %></li>
                      <li class="col text-nowrap"><%= link_to "New post(Lost)", new_post_lost_cat_path %></li>
                      <li class="col text-nowrap"><%= link_to "Lost cats", post_lost_cats_path %></li>
                      <li class="col text-nowrap"><%= link_to "My page", user_path(id: "my_page") %></li>
                      <li class="col text-nowrap"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
                    <% elsif admin_signed_in? %>
                      <li class="col text-nowrap"><%= link_to "Users", admin_top_path %>
                      <li class="col text-nowrap"><%= link_to "Types", admin_types_path %>
                      <li class="col text-nowrap"><%= link_to "Comments", admin_post_image_comments_path %>
                      <li class="col text-nowrap"><%= link_to "Posts", admin_post_images_path %>
                      <li class="col text-nowrap"><%= link_to "Log out",destroy_admin_session_path, method: :delete %>
                    <% else %>
                      <li class="col"><%= link_to "Sign up", new_user_registration_path %></li>
                      <li class="col"><%= link_to "Sign in", new_user_session_path %></li>
                      <li class="col"><%= link_to "Cats", post_images_path %></li>
                      <li class="col"><%= link_to "Lost cats", post_lost_cats_path %></li>
                    <% end %>
                  </ul>
                </div>
            </div>
          </div>
        </nav>
      </header>
      <main>
      <%= yield %>
      </main>
      <footer>
        <small>&copy; 2023 meow</small>
      </footer>
    </div>
  </body>
</html>